baseURL = "https://pawelgrzybek.com"
title = "pawelgrzybek.com"
disableKinds = ["section", "taxonomy", "term"]
pygmentsUseClasses = true
enableRobotsTXT = true

[params]
  description = "Hi there, I'm Pawel Grzybek, Software Engineer from Poland. Nowadays I live in Leicester (UK). When I'm not coding, I'm spinning funky vinyl records."

[frontmatter]
  date  = [":filename", ":default"]

[permalinks]
  posts = "/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats.RSS]
  baseName = "feed"

[outputFormats.JSON]
  baseName = "feed"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
