[build]
  publish = "public/"
  command = "rm -rf data && rm -rf public && mkdir data  && curl -o data/comments.json https://rbjvwgq51g.execute-api.eu-west-2.amazonaws.com/Prod/?access_token=$COMMENTS_SERVERLESS_ACCESS_TOKEN && hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.80.0"

[context.deploy-preview]
  command = "rm -rf data && rm -rf public && mkdir data  && curl -o data/comments.json https://rbjvwgq51g.execute-api.eu-west-2.amazonaws.com/Prod/?access_token=$COMMENTS_SERVERLESS_ACCESS_TOKEN && hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.80.0"
